<?
include 'config.php';
if($mysql) {
    $pdo = new PDO("mysql:host=".$mysql_host.";dbname=".$mysql_database,$mysql_user,$mysql_password);
} else {
    $pdo = new PDO("sqlite:db/jobs.db");
}
	
$marker       = "# generated by jobjoker *do not edit*";

function patch_crontab(){
	global $marker;
	$crontab      = array();
	$markerfound  = 0;
	exec("crontab -l", $old_crontab);
  foreach( $old_crontab as $k => $line )
		if( ( $markerfound == 1 ) || 
				( $markerfound == 0 && $line == $marker && $markerfound++ ) ||
			  ( $markerfound == 1 && $line == $marker ) )
			 unset($old_crontab[$k]);
	$crontab = array_merge($old_crontab, generate_crontab() );
	return implode("\n", $crontab);
}

function generate_crontab(){
	global $pdo, $marker, $config;
	$jobs    = array();
	$stmnt   = $pdo->prepare("SELECT * FROM job WHERE parameters LIKE ?");
	$query   = $stmnt->execute( array('%crontab%') );
	$jobs    = $stmnt->fetchAll();
	$crontab = array( $marker );
	foreach( $jobs as $job ){
		$json = json_decode($job['parameters']);
		if( $json == NULL ) continue;
		$crontab[] = $json->crontab." cd ".dirname(__FILE__)." && ".$config->php_command." run.php ".$job['id'];
	}
	$crontab[] = $marker;
	return $crontab;
}

// lets mashup the old crontab with the new crontab
file_put_contents("/tmp/crontab.jobjoker", patch_crontab() );
system("crontab /tmp/crontab.jobjoker && rm /tmp/crontab.jobjoker");

?>
